name: Test

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: test
        run: |
          yarn install --silent --non-interactive
          yarn test
        env:
          CI: true
          NOVE_ENV: test
